// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATm9dRMMkICUerpaq3bqan0sLgRSLWbZc',
    appId: '1:903046968774:android:20b251b238fa3253ce2ec7',
    messagingSenderId: '903046968774',
    projectId: 'jrmessanger-f374d',
    databaseURL: 'https://jrmessanger-f374d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jrmessanger-f374d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdFtkkM1BeuodstKUd6YkM46_hGLNQHE',
    appId: '1:903046968774:ios:7342e2d40e5b47d8ce2ec7',
    messagingSenderId: '903046968774',
    projectId: 'jrmessanger-f374d',
    databaseURL: 'https://jrmessanger-f374d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jrmessanger-f374d.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}